global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3001']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8001']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'cart-service'
    static_configs:
      - targets: ['cart-service:8002']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8003']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:8004']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'search-service'
    static_configs:
      - targets: ['search-service:8005']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8006']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:3002']
    metrics_path: /metrics
    scrape_interval: 30s